### ISSUE TITLE
please add support for Accept-Encoding's "br"

### ISSUE THREAD

**Issue by rushmj** [curlconverter/curlconverter#128]
if the Accept-Encoding of response has "br",it will has problem.you can use 「response.headers['Content-Encoding'] == 'br' 」to check and add some decode package like brotli,thank you

**Comment by verhovsky** [comment]
If you're talking about Python, then to support `br` these days, you just need to have the `brotli` package installed, like this `pip install brotli`. We now just comment out the `accept-encoding` header in the Python output, so that `requests` can set that header to whatever encodings it supports.

We could also add a comment telling users how to install `requests` when we see `br` in `Accept-Encoding` but meh.
