### ISSUE TITLE
Curl Converter needs a VSCode extension

### ISSUE THREAD

**Issue by csells** [curlconverter/curlconverter#147]
Quicktype has one -- why not us, too?!

**Comment by jgroom33** [comment]
Adding this to the Ansible plugin for VS Code
https://github.com/VSChina/vscode-ansible/pull/244

**Comment by verhovsky** [comment]
I created the extension:

https://marketplace.visualstudio.com/items?itemName=curlconverter.curlconverter

https://github.com/curlconverter/vs-code

It adds a "Paste cURL as code" Cmd-Shift-P command to VS Code and adds it to the right click menu under "Paste" when you're editing a language that curlconverter can convert to.

I'm thinking it might be annoying since curlconverter is not something most people would use that often and cluttering up the right click menu for that 1 time you want to use it isn't great. I'm open to suggestions on how to improve that UX. I wanted to add the entry to the right click menu only when the user's clipboard begins with "curl " but I couldn't figure out how to listen for right click events in VS Code. It's also not ideal since people might be confused why they sometimes see the entry and sometimes they don't, always having the entry and explaining "your clipboard must start with 'curl'" in an error message has its benefits.

I was unable to use the latest curlconverter code with tree-sitter because you [can't use ES6 modules](https://github.com/microsoft/vscode/issues/130367) [in Electron](https://github.com/electron/electron/issues/21457) and curlconverter needs to be an ES6 module because top-level `await` is the simplest way to initialize the tree-sitter Parser object, so the extension is shipping curlconverter 3.21.0.
