### ISSUE TITLE
Multiple cookies in headers, convert all?

### ISSUE THREAD

**Issue by cf512** [curlconverter/curlconverter#161]
At present, if converting a curl with multiple cookies in the headers, only the last one in the list gets included in the output.

Example input:

`curl 'https://httpbin.org/cookies' -H 'Cookie: authCookie=123' -H 'Cookie: authCookie2=12345' -H 'Cookie: authCookie3=123456'`

Opening this issue as a task to check further if this is the desired behavior or not.

**Comment by jgroom33** [comment]
the response i've seen from servers is that multiple cookie params are concatenated into a single cookie.

**Comment by verhovsky** [comment]
Normally there's only one cookie header and multiple cookies are separated by `;` like this: `-H 'Cookie: authCookie=123;authCookie2=12345;authCookie3=123456'`. If you passed multiple `-H 'Cookie: <blah>` headers, we would generate code like this

```py
import requests

headers = {
    'Cookie': 'authCookie=123',
    'Cookie': 'authCookie2=12345',
    'Cookie': 'authCookie3=123456',
}

response = requests.get('https://httpbin.org/cookies', headers=headers)
```

which has the same effect as only including the last header when you run the code, but at least now users have a chance to notice the issue. Requests doesn't allow you to pass a list of tuples for `headers=` like you can for `params=`.

Instead of expecting everyone to know the syntax of the Cookie header and editing the cookies together with `;` themselves, it would be most helpful if we did something trivial like `'Cookie: ' + [request.headers.filter(h => h[0].toLowerCase() === 'cookie').map(h => h[1]).join(';')`, we could even include the other headers but comment them out, but that would send a different request than the curl command... but I'm not convinced if this is a real issue.
