### ISSUE TITLE
Add issue creation template

### ISSUE THREAD

**Issue by jgroom33** [curlconverter/curlconverter#186]
New issues in this repo frequently state:
"This does not convert to python" ... followed by a massive curl request.

The user opening a simple issue should be instructed to narrow down the curl request into the specific portion of the curl request that is causing the failure.

**Comment by jgroom33** [comment]
@romadrutskii looks like you are doing some issue cleanup.  Would you like to tackle this issue?

**Comment by NickCarneiro** [comment]
> The user opening a simple issue should be instructed to narrow down the curl request into the specific portion of the curl request that is causing the failure.

I want to build this into the UI of the web app, kind of like in SQL where it tells you exactly where the syntax error was. This should cut down on overall volume of tickets created.

**Comment by verhovsky** [comment]
The website has had a "pre-fill new issue from current output" issue template for a while which I think some people have made use of, though we should probably warn them not to redact cookies in the request or redact them for them... We could also add a "privately email us your broken command" mailto: link, because more people have email than a GitHub.

I think there's not enough tickets. We should optimize the amount of people with issues that are telling us about their issues, not the quality of how they're telling us about them. I would rather have the broken command and no explanation/expected output than an explanation and no command because you can step through the former in a debugger, but it's even nicer when we get both. Most people already have to create a github account just to submit a broken command, which is a lot of work.

Lots of people fail to even paste their command properly, if we make them try to figure out where the error is, that would just lead to even less people submitting issues. There's way more issues happening than we get to see on the tracker. We should be making it as easy as possible for people to submit their broken commands and we can always close the noise.

> kind of like in SQL where it tells you exactly where the syntax error was

It will be a lot of work keep track of our location while parsing and to propagate it back and I think most of the time it won't actually be helpful because it will just point to the end and say `no URL specified` or the error happens during code generation, not argument parsing and at that point it would be lots of work to store the position in the source for each argument, but it would be really great to do this.

**Comment by NickCarneiro** [comment]
In hindsight, I agree. The positional errors proposal isn't realistic.

If the goal is to increase our intake, we could add a `Report` button with a public/private toggle in a modal.

I would consider the following channels, arranged in order of difficulty:
- Email
- Google form / hosted no-code service
- Our own backend

On the other hand, the site currently makes no ajax calls. That's a nice property for privacy, but getting more reports is a worthy goal.

Speaking pragmatically, I'm not about to leap in to action and implement any of this. Adding a private email link is a quick win and can be done immediately.
