### ISSUE TITLE
Optimization dependencies: yargs

### ISSUE THREAD

**Issue by wll8** [curlconverter/curlconverter#246]
You used the project [NickCarneiro/yargs](https://github.com/NickCarneiro/yargs) from [yargs/yargs](https://github.com/yargs/yargs) and modified it.
- Your branch is behind yargs a lot. This may cause some defects in yargs that cannot be repaired.
- `"yargs": "github:NickCarneiro/yargs"` will cause slow downloads in many places, because the repository needs to be cloned from github and there is no version guarantee. It is recommended that you merge the code of yargs and consider publishing to npm.

> [curlconverter@2.16.0 › yargs@github:NickCarneiro/yargs] install yargs from git github:NickCarneiro/yargs, may be very slow, please keep patience

![image](https://user-images.githubusercontent.com/28223260/101589951-6d2f9280-3a24-11eb-948a-ffa57a3cbddd.png)

**Comment by verhovsky** [comment]
> Your branch is behind yargs a lot

The fork has been updated multiple times, so this is no longer true.

> It is recommended that you merge the code of yargs and consider publishing to npm

You are right, so we did it. Our forks are now published as [`@curlconverter/yargs`](https://www.npmjs.com/package/@curlconverter/yargs) and [`@curlconverter/yargs-parser`](https://www.npmjs.com/package/@curlconverter/yargs-parser) and `curlconverter` now depends on them instead of a Git URL.
