### ISSUE TITLE
"Content-Type" makes Python requests fail

### ISSUE THREAD

**Issue by lucahammer** [curlconverter/curlconverter#248]
I am not really sure if it is an issue or not, but it took me several hours to figure out what went wrong, so I wanted to share it with others. I converted a curl command, which contained "Content-Type: multipart/form-data", but always got a 500 error when I used it in Python request. After learning that Python requests automatically determines the correct content type, I removed it and finally everything worked. 

curl command:
`curl https://url.com/v1/files -X POST -H "Authorization: Bearer 123" -H "Content-Type: multipart/form-data" -H "Accept: application/json" -F "file=@filename.pdf" -F "type=thing"`

Failing Python requests:
```
import requests

headers = {
    'Authorization': 'Bearer 123',
    'Content-Type': 'multipart/form-data',
    'Accept': 'application/json',
}

files = {
    'file': ('filename.pdf', open('filename.pdf', 'rb')),
    'type': (None, 'thing'),
}

response = requests.post('https://url.com/v1/files', headers=headers, files=files)
```

Working Python requests:
```
import requests

headers = {
    'Authorization': 'Bearer 123',
    'Accept': 'application/json',
}

files = {
    'file': ('filename.pdf', open('filename.pdf', 'rb')),
    'type': (None, 'thing'),
}

response = requests.post('https://url.com/v1/files', headers=headers, files=files)
```

**Comment by lucahammer** [comment]
Just realized, that this is a duplicate of #52. Sorry.

**Comment by NickCarneiro** [comment]
Thanks for linking the other issue. Maybe the best move for curlconverter is to add a warning to the UI or a comment in the output.

**Comment by verhovsky** [comment]
> I removed [the header] and finally everything worked

Since this was the right step for @lucahammer, that's what curlconverter should do for you as well.  Warning users that we're doing it is a good idea but we don't have a way to do that (yet).

I [checked the Requests source code](https://github.com/urllib3/urllib3/search?q=boundary) and they seem to [only add it for `multipart/formdata`](https://github.com/urllib3/urllib3/blob/9344db2162082a4bc211c44f8675597eff971d9c/src/urllib3/filepost.py#L64) (it would be more correct to add a `boundary` for any `multipart/*` types, like [`multipart/byteranges`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#multipartbyteranges)) so that makes pretty easy.
