### ISSUE TITLE
Availability through PyCharm

### ISSUE THREAD

**Issue by michaeletro** [curlconverter/curlconverter#322]
It would be great if this was available through PyCharm. Having trouble downloading the package and love the website emulator

**Comment by verhovsky** [comment]
Could you share exactly what you're having trouble with when downloading the package?

I agree, this definitely needs to be packaged as an extension. I'll make one for VS Code.

**Comment by michaeletro** [comment]
I appreciate your timely response!

So I have a couple of questions, is this package strictly for JavaScript? I
am tinkering with automating CURL requests with Python and love how your
web page filters and sorts through the Raw CURL request so elegantly. It
would be superb if a library for Python to work with your code. Secondly,
do we need permission to pull from the source code? I am getting an error
message stating I need to request permission to pull.

Nonetheless, your work here is pretty excellent. I have been tinkering with
alternative solutions to retrieving, filtering, classifying, and automating
CURL requests, and your page is a blessing.

**Comment by verhovsky** [comment]
curlconverter can also be used from the command line, but that's not really what you're asking.

**Comment by verhovsky** [comment]
curlconverter can be used from the command line, not just JavaScript. It also has a JSON output, which outputs a representation of the input command after the first step of parsing, though it's not as good as it could be.

So you could call it like this from Python through [`subprocess`](https://docs.python.org/3/library/subprocess.html)

```py
import subprocess
import json

result = subprocess.run(['curlconverter', '--language', 'json', 'example.com'], capture_output=True)
result = json.loads(result.stdout)
print(result) # {'url': 'http://example.com', 'raw_url': 'http://example.com', 'method': 'get'}
```

or alternatively

```py
import subprocess
import json

def parse_curl(command):
    result = subprocess.run(['curlconverter', '--language', 'json'], text=True, input=curl_command, capture_output=True)
    return json.loads(result.stdout)

print(parse_curl("curl --data helloworld example.com")) # {'url': 'http://example.com', 'raw_url': 'http://example.com', 'method': 'post', 'data': {'helloworld': ''}}
```

Note that you'll need to install the preview version of curlconverter for the new command line interface, which you can do with

```
npm install -g curlconverter@next
```

http://curlconverter.com/ also links to other project (scroll to the bottom) that try to do the same thing. There is a Python `uncurl` library, but I've never used it and have no idea how good it is.

>  am getting an error message stating I need to request permission to pull

if I understood correctly, I bet it's because you're pulling (cloning) over SSH and don't have [an SSH key configured for github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh). The fastest thing would be to use HTTP:

<img width="467" alt="Screen Shot 2022-01-07 at 3 51 19 AM" src="https://user-images.githubusercontent.com/5687998/148540298-387a669c-5cee-404b-9f64-aa82467da88e.png">

i.e.

```
git clone https://github.com/curlconverter/curlconverter.git
```

**Comment by verhovsky** [comment]
I created the VS Code extension: https://github.com/curlconverter/curlconverter/issues/147#issuecomment-1008482048

**Comment by michaeletro** [comment]
Excellent!

Your code snippet ended up working haha but in my frustration I ended up
writing a filtering algorithm to filter a raw CURL text into headers,
cookies, data etc. based off of their set haha so I am parsing networking
requests pretty efficiently.

My next step is to be able to retrieve individual JSON variables to replace
them with my own inputs and use the same network requests to extract
different data points with my inputted variables.

I might be reinventing the wheel, but it is still an interesting project to
work on.

I will check out your VS Code extension! Your website does it pretty
amazingly! Thank you for your support as well.

**Comment by verhovsky** [comment]
I'm closing this as wontfix because there's a VS Code extension now and I'm not going to work on a PyCharm extension.

If someone wants to make one, they obviously can.
