### ISSUE TITLE
bug (python): post requests "data" with boolean logic in string incorrectly converted to dictionary instead of string 

### ISSUE THREAD

**Issue by holts-shoe** [curlconverter/curlconverter#334]
Thank you for this amazing tool you have created. I found a very small bug:

Currently:
`--data-raw '{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}' \`

Converts to a dictionary:
```
data = {
  '{"filters":"start_date <': ' 1647270397 AND end_date > 1647269497"}'
}
```

When it should convert to a string:
`'{"filters":"start_date <': ' 1647270397 AND end_date > 1647269497"}'`

**Comment by verhovsky** [comment]
The issue is that `--data` isn't always a query string, even though it gets sent as `application/x-www-form-urlencoded`. Curl sends along the `--data` as you passed it in the command line, whereas we want to convert it to a dict for easier editing and requests, when passed a dict, url encodes the keys/values (see below).

There's no reliably way to distinguish between whether or not the input string is actually meant to be a query string or just text that happens to have a `=`/`&` in it, i.e. to tell if converting `data` to a dict would be useful, so we'll have to add a comment with the original data any time we convert it to a dictionary...

```py
# data = '{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}'
data = {
  '{"filters":"start_date <': ' 1647270397 AND end_date > 1647269497"}'
}
```

We could add some heuristics like `if (dataString.count('=') === dataString.count('&') + 1 && dataString.count('=') > 2` then it's probably a query string and we can omit the comment, or if the data contains any characters that would be url encoded, we can assume it's not a query string, but these won't work that well.

---

Using `nc -kl 8888` and then running this command (`--data` or `--data-raw` doesn't matter, the `-raw` only changes whether or not an `@` character causes the data to be interpreted as a filename).

`curl --data-raw '{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}' localhost:8888`

we can see that this is the data curl sends:

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.77.0
Accept: */*
Content-Length: 64
Content-Type: application/x-www-form-urlencoded

{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}
```

and running the resulting program

```py
import requests

data = {
  '{"filters":"start_date <': ' 1647270397 AND end_date > 1647269497"}'
}

response = requests.post('http://localhost:8888', data=data)
```
requests will url encode the data

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 82
Content-Type: application/x-www-form-urlencoded

%7B%22filters%22%3A%22start_date+%3C=+1647270397+AND+end_date+%3E+1647269497%22%7D
```

though I think if you actually try running that Python code as-is, you might still get the correct result from the server, since presumably the server does url-decoding before processing the data. 

Running the corrected program

```py
import requests

data = '{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}'

response = requests.post('http://localhost:8888', data=data)
```

we get

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 64

{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}
```

**Comment by verhovsky** [comment]
So what I ended up doing is this

> if the data contains any characters that would be url encoded, we can assume it's not a query string

which means we don't parse a lot of querystrings into a dict anymore, but hopefully matching the request is more useful to people than getting a slightly different request that's harder to edit. I also made it add the `Content-Type` header, so now your request gets converted how you expected (at the expense of people that would be okay with a slightly different request but being able to edit it as a Python dictionary)

```py
import requests

headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
}

data = '{"filters":"start_date <= 1647270397 AND end_date > 1647269497"}'

response = requests.post('http://localhost:8888', headers=headers, data=data)
```
