### ISSUE TITLE
Support for multipart/form-data

### ISSUE THREAD

**Issue by KohnoseLami** [curlconverter/curlconverter#355]
multipart/form-data can be sent cleanly using an external module
Can these be generated automatically?

```
import requests
import random,string
from requests_toolbelt import MultipartEncoder

fields = {
    'file': ('test.png', your_data, "image/png"),
    'file_id': "0"
}
boundary = '----WebKitFormBoundary' \
           + ''.join(random.sample(string.ascii_letters + string.digits, 16))
m = MultipartEncoder(fields=fields, boundary=boundary)

headers = {
    "Host": "xxxx",
    "Connection": "keep-alive",
    "Content-Type": m.content_type
}

req = requests.post('https://xxxx/api/upload', headers=headers, data=m)
print(req.text)
```

**Comment by verhovsky** [comment]
Are you having issues with your curl command? Because we already support `form-data`. Requests doesn't need that helper https://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file

https://github.com/curlconverter/curlconverter/blob/4129d6b885f94115e69a72efb321561debed744d/fixtures/curl_commands/multipart_post.sh

https://github.com/curlconverter/curlconverter/blob/4129d6b885f94115e69a72efb321561debed744d/fixtures/python/multipart_post.py

Looks like the point of `requests_toolbelt.MultipartEncoder` is to stream files while uploading. I think people that need that should do it themselves. We generate code like this 

```py
import requests

headers = {
    'Authorization': 'Bearer ACCESS_TOKEN',
}

files = {
    'attributes': (None, '{"name":"tigers.jpeg", "parent":{"id":"11446498"}}'),
    'file': ('myfile.jpg', open('myfile.jpg', 'rb')),
}

response = requests.post('https://upload.box.com/api/2.0/files/content', headers=headers, files=files)
```

and they'd have to add the import statement, wrap the `files = {` part in a `MultipartEncoder(` and copy over the `Content-Type: multipart/form-data` with the boundary into a boundary. We want to generate code that makes a request that closely matches the one curl makes, we can't be generating random boundaries for people.
