### ISSUE TITLE
how can I solve this problem that requests the wasm file for 404?

### ISSUE THREAD

**Issue by ljw-kr** [curlconverter/curlconverter#422]
![image](https://user-images.githubusercontent.com/52630138/180946475-3b0e97f9-464a-4f9e-80bb-b4f5d29733a4.png)

**Comment by verhovsky** [comment]
When you `npm install curlconverter`, tree-sitter.wasm is in node_modules/web-tree-sitter and tree-sitter-bash.wasm is in node_modules/curlconverter. You need to copy these two files from node_modules into the directory your server is serving so that they can be downloaded as `http://yourdomain.com/tree-sitter.wasm` and `http://yourdomain.com/tree-sitter-bash.wasm`. You can see how we do it for https://curlconverter.com with webpack here:

https://github.com/curlconverter/curlconverter.github.io/blob/b35bc2b78fdae9e6c4c7e8ab781bd8de633e1f47/webpack.config.js#L53-L54

The fact that the file must be at top level path (and not `http://yourdomain.com/static/tree-sitter.wasm` for example) is hard coded in curlconverter here

https://github.com/curlconverter/curlconverter/blob/aa0dba4ec34c69796c5bfd12b46c3d7fe4646f28/src/bash-parser-web.ts#L6

and probably in a similar way by web-tree-sitter.
