### ISSUE TITLE
Copy all requests as cURL

### ISSUE THREAD

**Issue by mujtabaxd** [curlconverter/curlconverter#443]
Can we do this?
Copy all requests as curl and convert them to python etc.

![Screenshot (13)](https://user-images.githubusercontent.com/34020024/188443637-84b056f1-fed3-455b-bac1-aced165237c4.png)

**Comment by Mariownyou** [comment]
Can you explain your proposal more detailed, please

**Comment by verhovsky** [comment]
The proposal is straight forward. You can right click and copy all requests that were made to load a website in chrome. @mujtabaxd is asking curlconverter to support converting multiple commands in the input.

```
curl example.com
curl example.com/2
```

->

```py
import requests

requests.get('http://example.com')
requests.get('http://example.com/2')
```

currently we just do the first one and warn that the rest of the input is not used.

This would be quite easy to do, especially if you don't care about not repeating the `import` statement. My reason for not doing it is mostly because I do care about not repeating the import statement and because I personally don't really see the use case for it.
