### ISSUE TITLE
can export method parseCurlCommand ?

### ISSUE THREAD

**Issue by iyaozhen** [curlconverter/curlconverter#501]
I have myself data structure, `toJsonString` not implementation all `Request`, loss some infomation, like `followRedirects`.

**Comment by verhovsky** [comment]
I've planned to do this for a while, I haven't done it yet because I'm still working on the parser so I change how the `Request` object looks all the time and I don't want to worry about making my changes backwards compatible until I'm finished with the parser. If you're okay with `Request` and `parseCurlCommand` being undocumented and changing completely without warning, I can export it for you in the next release.

**Comment by iyaozhen** [comment]
I download this code in my project, work around it.

In the process of processing `Request` to my data structure, i find `curl` optinons is very complex. As you say, `Request` must be robustness, and then export it.

Thx again, pls forgive me poor english.
