### ISSUE TITLE
Some switches are unsupported for wget

### ISSUE THREAD

**Issue by lonix1** [curlconverter/curlconverter#573]
e.g. curl's `-s` / `--silent` and `-f` / `--fail`. The tools reports:
> --foo is not a supported option

There are meaningful conversions, like `--quiet`, `--no-verbose`, etc.

BTW: just found this tool, and it's brilliant. So helpful. Thank you!

**Comment by verhovsky** [comment]
I added the arguments you mentioned except `--fail` because I couldn't find what the equivalent wget option is. In general, curlconverter maintains the defaults of the runtime it converts to. So for example wget is `--verbose` by default and curl is `--no-verbose` by default, but unless you pass `curl --no-verbose example.com` as the input command (which normally doesn't make sense, why would you tell curl to behave the way it already behaves?) the generated wget command will not include `--no-verbose` and will print verbose output, it's default. Some more details in the readme:

> - curl doesn't follow redirects or decompress gzip-compressed responses by default, but the generated code will do whatever the default is for that runtime, to keep it shorter. For example Python's Requests library [follows redirects by default](https://requests.readthedocs.io/en/latest/user/quickstart/#redirection-and-history), so unless you explicitly set the redirect policy with `-L`/`--location`/`--no-location`, the generated code will not handle redirects the same way as the curl command

Also, curl and wget both have about 250 options

https://curl.se/docs/manpage.html

https://www.gnu.org/software/wget/manual/wget.html

matching them up is a lot of work (62500 comparisons lol), so if there's more that should be supported, it would save me some time if you were more specific.
