### ISSUE TITLE
Added Chrome Extension

### ISSUE THREAD

**Issue by r3x5ur** [curlconverter/curlconverter#637]
[curlconverter-crx.zip](https://github.com/curlconverter/curlconverter/files/14442425/curlconverter-crx.zip)
- download this file and unzip
- open `chrome://extensions/`
- enable developer mode
- load the unzipped extension
![image](https://github.com/curlconverter/curlconverter/assets/64947085/f942eab0-e530-45af-b9a1-91c17dfdd99a)

**Comment by verhovsky** [comment]
Huh, there's a `chrome.devtools.network.getHAR()` and `chrome.devtools.network.onRequestFinished`, so we could we could re-implement the entire Network panel and then add a way to copy the requests as various languages.

https://developer.chrome.com/docs/extensions/reference/api/devtools/network

It would require adding a HAR frontend to curlconverter instead of just curl commands. Might as well add a raw HTTP frontend too at that point like https://ryan.govost.es/http-translator/
